### ISSUE TITLE
Document title Updating... broken?

### ISSUE THREAD

**Issue by etpinard** [plotly/Dash.jl#101]
Consider

```jl
# main.jl
using Dash, DashHtmlComponents

external_stylesheets = ["https://codepen.io/chriddyp/pen/bWLwgP.css"]

app = dash(;external_stylesheets)

app.layout = html_div() do
    html_button("CLICK ME"; id="btn"),
    html_div(id="output")
end

callback!(app,
          Output("output", "children"),
          Input("btn", "n_clicks")) do n_clicks
    if isnothing(n_clicks)
        return ""
    end
    sleep(5)
    return "Number of clicks: $n_clicks"
end

run_server(app, "0.0.0.0", debug=true)
```

and the following envs:

```
# base
  [1b08a953] Dash v0.1.3
  [1b08a953] DashHtmlComponents v1.1.3
```

and

```
# dev
  [1b08a953] Dash v0.1.4 `https://github.com/plotly/Dash.jl.git#dev`
  [1b08a953] DashHtmlComponents v1.1.3
```

Then `julia --project=base main.jl` gives:

![Peek 2021-05-05 12-02](https://user-images.githubusercontent.com/6675409/117172430-cf08e400-ad99-11eb-97a4-ebe704c1f276.gif)

but with `julia --project=dev main.jl` we get

![Peek 2021-05-05 12-04](https://user-images.githubusercontent.com/6675409/117172752-18f1ca00-ad9a-11eb-93b1-02c133b3b72e.gif)

**Comment by etpinard** [comment]
https://github.com/plotly/Dash.jl/pull/99 seems to have caused the problem.

Things worked fine on https://github.com/plotly/Dash.jl/commit/7b6c06b5f6f2334bec718a0293c6bccd8542bde3 off the `dev` branch.

**Comment by alexcjohnson** [comment]
Nice catch @etpinard ! We probably need an update here due to https://github.com/plotly/dash/pull/1315
