### ISSUE TITLE
Make dash_bootstrap_components.themes available in Dash.jl

### ISSUE THREAD

**Issue by tsela** [plotly/Dash.jl#11]
Hi all,

First, let me tell you how fantastic the work you've done so far is. I've been playing with Dash.jl for a few days now and it's incredible how seamless the experience is. Also, I think it's great you've added the components from the dbc library.

However, those components only work properly if you include a Bootstrap v4 stylesheet from [BootstrapCDN](https://www.bootstrapcdn.com/). For this reason, the Python library provides the `dash_bootstrap_components.themes` module, with a number of free stylesheets from Bootstrap and from the Bootswatch gallery (see https://dash-bootstrap-components.opensource.faculty.ai/docs/themes/ for more info). It's a simple list of URL constants, but it's very practical as you don't have to hunt for the URLs yourself for at least that selection of stylesheets.

So I think it'd be great if Dash.jl could provide the same facility, maybe as a `dbc_themes` struct or NamedTuple, or whatever you feel fits best with how Dash.jl is supposed to work (I'm unfortunately not yet knowledgeable enough about Julia and the specific implementation of this library to be able to implement this myself).

What do you think?

**Comment by waralex** [comment]
Hi!
Thank you for your nice words about Dash. I am currently actively working on bringing the api and behavior of this package in line with the rest of the dash implementations. I.e., on converting my Dashboards.jl package  in Dash.jl. So a lot of things will change soon. If the issue with dash_bootstrap_components.themes is not resolved automatically as part of these changes, then I will definitely return to it, because I think Bootstrap is a very important set of components.

**Comment by tsela** [comment]
Great! Thanks.

**Comment by rpkyle** [comment]
@waralex @tsela Some good news on this front: @tcbegley has contributed plotly/dash#1125, which @Marc-Andre-Rivet has been reviewing this week. 

Once plotly/dash#1125 is merged, the Julia component generator is working, and Dash.jl supports components generated using it, we can build `DashBootstrapComponents.jl` for Julia more or less as we would for Python and R.

**Comment by waralex** [comment]
There is a small problem here that dash_bootstrap_components.themes is a part of the Python api of dash_bootstrap_components itself that is not created using the generator. So, apparently, we will have to ask the author to add a similar code to the package on Julia, which, for example, I can write

**Comment by rpkyle** [comment]
> There is a small problem here that dash_bootstrap_components.themes is a part of the Python api of dash_bootstrap_components itself that is not created using the generator. So, apparently, we will have to ask the author to add a similar code to the package on Julia, which, for example, I can write

In the past, we have handled this by writing logic to retain human-authored code which was already present within the repository's source directory, and making whichever changes were required to the package definitions to enable their inclusion at generation time. We currently include `df_to_list` within `dashTable`, and `dashbioManhattan`/`dashbioVolcano` inside of `dashBio` using this approach. It turns out that we can have it both ways 🙂

**Comment by rpkyle** [comment]
Good news on this front: plotly/dash#1203 was recently merged, so we are well on our way to being able to build `DashBootstrapComponents.jl` in the not-so-distant future.

**Comment by tcbegley** [comment]
> We currently include `df_to_list` within `dashTable`, and `dashbioManhattan`/`dashbioVolcano` inside of `dashBio` using this approach.

@rpkyle could you point me in the right direction to learn more about how this works? I couldn't quite figure it out looking at the `dash-table` repo.

**Comment by rpkyle** [comment]
@tcbegley Sure thing -- this is the Python code which currently finds these functions:

https://github.com/plotly/dash/blob/599cccb50b3d90081a9ce68635c6c9a736162296/dash/development/_r_components_generation.py#L762-L798

It's R-specific, but there's no reason we couldn't implement similar functionality in the Julia component generator. The code block linked above is able to locate the function saved here, within its own script:

https://github.com/plotly/dash-table/blob/master/R/df_to_list.R

We then export functions from the package into the `NAMESPACE` file using the `export_string` line below:

```
export_string += "\n".join("export({})".format(function) for function in fnlist)
```

**Comment by tcbegley** [comment]
That's great, thanks!

**Comment by jackparmer** [comment]
Once this is working, note-to-self to make sure "Dash for Julia" is added to the sidebar here:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/1865834/88720872-9265d900-d0f3-11ea-8b0a-9cb91e5764bf.png">
https://dash-bootstrap-components.opensource.faculty.ai/docs/dashr/

**Comment by rpkyle** [comment]
I've opened a PR to add support for Dash.jl via https://github.com/facultyai/dash-bootstrap-components/pull/464.

**Comment by tcbegley** [comment]
Hey all,

This has now been done so this issue can be closed. See facultyai/dash-bootstrap-components#519.

It's also documented in the [Quickstart](https://dash-bootstrap-components.opensource.faculty.ai/docs/) in our docs.

**Comment by tsela** [comment]
Wow great! Happy to see this resolved. This brings Dash.jl ever closer to being on par with Python Dash!
