### ISSUE TITLE
typo in docs https://dash-julia.plotly.com/basic-callbacks

### ISSUE THREAD

**Issue by mzaffalon** [plotly/Dash.jl#122]
I am not sure if the site https://dash-julia.plotly.com/basic-callbacks belongs to you.

I would like to report a typo in the the example in the section **Dash App With Multiple Inputs**.
`xaxis_type = xaxis_type == "Linear" ? "linear" : "log",` should read `xaxis_type = xaxis_type == "linear" ? "linear" : "log",` and similarly for the `yaxis_type`.

**Comment by sglyon** [comment]
This has been fixed and should be deployed soon!
