### ISSUE TITLE
broken link in documentation

### ISSUE THREAD

**Issue by mzaffalon** [plotly/Dash.jl#124]
From https://dash-julia.plotly.com/dash-core-components, if I click on "Graph" on the menu on the right hand side and then on the title Graph, I am directed to https://dash-julia.plotly.com/dash_core_components/graph but the page is the root page ![image](https://user-images.githubusercontent.com/1351814/130293628-0749e741-dc1b-4598-a6d0-915a471c9909.png)

**Comment by etpinard** [comment]
appears to be fixed - closing
