### ISSUE TITLE
How to update Input via HTTP request?

### ISSUE THREAD

**Issue by cserteGT3** [plotly/Dash.jl#145]
I just started play around with Dash.jl and I'm trying to update the plots regularly with a trigger from different server. (I know I could use [dcc.Interval](https://dash.plotly.com/live-updates)).
Based on the package's [tests](https://github.com/plotly/Dash.jl/blob/55ee5503557822d4b2858d092b00fd8ea6aa6587/test/callbacks.jl#L151), I came up with the following example, but it doesn't work. (Spoiler: I have no clue how HTTP requests work),

Server code:
```julia
using Dash
app = dash()
app.layout = html_div() do
    dcc_input(id = "my-id", value="initial value", type = "text"),
    html_div(id = "my-div")
end
callback!(app, Output("my-div", "children"), Input("my-id", "value")) do value
    return value
end
run_server(app, debug=true)
```

"Client" code with output
```julia
julia> using HTTP

julia> test_json = """{"output":"my-div.children","changedPropIds":["my-id.value"],"inputs":[{"id":"my-id","property":"value","value":"test"}]}"""
"{\"output\":\"my-div.children\",\"changedPropIds\":[\"my-id.value\"],\"inputs\":[{\"id\":\"my-id\",\"property\":\"value\",\"value\":\"test\"}]}"

julia> r = HTTP.post("http://127.0.0.1:8050/_dash-update-component", [], Vector{UInt8}(test_json));

julia> println(r.status)
200

julia> println(r.body|>String)
{"response":{"my-div":{"children":"test"}},"multi":true}
```

The above response complies with the tests, but it doesn't update in the browser.

I would appreciate any help with this topic, but first of all: should this method work? Can I trigger somehow Input field/variable updates?

**Comment by waralex** [comment]
Hi @cserteGT3 !
>should this method work?

No, this method will not work. 
Request for `_update_component`  works as follows - when the `js` code on the front-end (in the browser) understands that some property of the element that appears in the  some `Input` of Dash callbacks has changed, it sends this request to start the execution of the callback, gets back its result (new values for the properties specified in the `Output`) and updates the values of these properties.  
So by sending this request with your hands from another server, you just get a json response with new output values.

**Comment by waralex** [comment]
>Can I trigger somehow Input field/variable updates?

The task is not very clear to me. I.e., there is one Dash server, and there can be many open dashboards by different users and they can be filled in different ways at the moment. What should happen when the Dash server receives such a request from another server? Should all dashboards open to all users be updated?

**Comment by cserteGT3** [comment]
Okay, thanks for the clarification.

The way I put my question was maybe misleading. Basically I have a stream
of data and I want to update the dashboard when a new datapackage arrives.
At the dash example page I didn't find an  example for it. If I understood
correctly, every example updates regularly (watching the dcc.interval
variable), but I would prefer to update when a new datapackage arrives. So
I'm looking for somekind of trigger mechanism to initiate the update. (For
example to trigger a callback, that reads the new values from a file.)

The dashboard will run on a homeserver, and I will be the only user, so in
theory updating the dashboard shouldn't cause any issues.

**Comment by waralex** [comment]
The fact is that the server (this generally applies to all http servers) does not know about the pages in the browsers that work with it and cannot execute their refresh itself. It can only respond to incoming requests. Therefore, the page itself should regularly request the server about whether there are any updates. The most logical way to do this is to use `dcc_interval`

I.e. `ddc_interval` regularly sends requests to its callback (you can do it quite often, for example several times a second) In the callback, you will check whether new data has appeared. If not, then immediately return `no_update()` (or throw a `PreventUpdate` exception). If the new data has appeared, then you read it from disk and do all the other things you need to do

**Comment by cserteGT3** [comment]
Allright, thank you for the description. Now I know a bit more about http servers. I'll then do this frequent checking with `no_update()`/`PreventUpdate`.

Thank you for your help!
