### ISSUE TITLE
Support for passing functions as layout (dynamic layouts)

### ISSUE THREAD

**Issue by rpkyle** [plotly/Dash.jl#15]
As with the other implementations of Dash, Dash.jl should support passing functions (not just components) to `layout`. This is described in more detail (Dash for Python) in https://github.com/plotly/dash-docs/issues/172 and https://github.com/plotly/dash-docs/pull/201.

**Comment by rpkyle** [comment]
This was resolved by #18, closing.

**Comment by alexcjohnson** [comment]
Does this actually work the same way as in Python? What I mean is, when layout is a function in Python, every time a user requests the app index page, the layout function executes again - so in principle you can use that to refresh a database query or something.

It looks to me as though in the [current Julia implementation](https://github.com/plotly/Dash.jl/pull/18/files#diff-fb3627f4c5a6ce541df30c46eed02a47L305) this function is only evaluated when you start the server. Am I interpreting this correctly?

**Comment by waralex** [comment]
@alexcjohnson 
```
layout_data(layout::Component) = layout
layout_data(layout::Function) = layout()
function process_layout(request::HTTP.Request, state::HandlerState)
            body = 
    return HTTP.Response(
        200,
        ["Content-Type", "application/json"],
        body = JSON2.write(layout_data(state.app.layout))
    )
end
```

function `layout_data` have 2 overloads (methods in Julia terms) - one used if `layout` is a Component and another if `layout` is  a function

**Comment by alexcjohnson** [comment]
OK great - just wanted to check. Looks like we are indeed all set 🎉 

> To be honest, I didn't really understand how layout is related to the index_page query, which generates only the basic html of the page.

Yes, that's right, the layout isn't *in* the index page, but it only gets refreshed during the initial load sequence, via the `_dash-layout` request.
