### ISSUE TITLE
How to custom hover in julia? 

### ISSUE THREAD

**Issue by HackYardo** [plotly/Dash.jl#152]
I need to custom hover event callback into to make a game GUI, but the doc has no section about it.
The python-dash doc has a [section](https://dash.plotly.com/vtk/click-hover), but I can not translate them into julia to make it works.

**Comment by waralex** [comment]
Hi!
Have you tried the example from the same section on Julia https://dash.plotly.com/julia/vtk/click-hover  ? 
If it does not work, or does not allow you to solve your problem, then write, I will try to figure out how to help you :)

**Comment by HackYardo** [comment]
1. I'm sorry, I didn't see the doc [page](https://dash-julia.plotly.com/interactive-graphing) closely. Its "Current Limitations" says:
  - It is **not currently possible to customize the style of the hover** interactions or the select box. This issue is being worked on in https://github.com/plotly/plotly.js/issues/1847.
2. I switch on another way to do the same thing without customizing hover.
3. The DashVtk is not the PlotlyJS(dcc_graph of Dash), so it off topic.

Thanks you a lot. I close the issue because it is a wrong issue.
