### ISSUE TITLE
Cant install in julia version 1.6.0

### ISSUE THREAD

**Issue by ravitejapavuluri** [plotly/Dash.jl#155]
When I tried to install with these set of lines:
using Pkg
Pkg.add(PackageSpec(url="https://github.com/plotly/DashBase.jl.git"))
Pkg.add(PackageSpec(url="https://github.com/plotly/dash-html-components.git", rev="master"))
Pkg.add(PackageSpec(url="https://github.com/plotly/dash-core-components.git", rev="master"))
Pkg.add(PackageSpec(url="https://github.com/plotly/dash-table.git", rev="master"))
Pkg.add(PackageSpec(url="https://github.com/plotly/Dash.jl.git", rev="dev"))

**it gives an error**:
Unsatisfiable requirements detected for package DashHtmlComponents [1b08a953]:
 DashHtmlComponents [1b08a953] log:
 ├─possible versions are: 1.1.4 or uninstalled
 ├─restricted to versions * by Dash_proj [1513d59c], leaving only versions 1.1.4
 │ └─Dash_proj [1513d59c] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─Dash_proj [1513d59c] is fixed to version 0.1.0
 ├─DashHtmlComponents [1b08a953] is fixed to version 1.1.4
 └─restricted to versions 2 by Dash [1b08a953] — no versions left
   └─Dash [1b08a953] log:
     ├─possible versions are: 1.1.1 or uninstalled
     └─Dash [1b08a953] is fixed to version 1.1.1

**Comment by waralex** [comment]
Hi!
It can be done much easier - `Pkg.add("Dash")`

What you wrote is installing a development version. This description is outdated, thanks for the reminder - I will rewrite it. In any case, at the moment the development version corresponds to the latest release
