### ISSUE TITLE
Redundant words of selectionStart docstring

### ISSUE THREAD

**Issue by HackYardo** [plotly/Dash.jl#159]
![image](https://user-images.githubusercontent.com/57677458/148645932-c8c428bc-1b7c-4e46-927d-9a765607b900.png)

**Comment by etpinard** [comment]
Appears fixed.

```jl
help?> dcc_input
```

now shows

![image](https://github.com/plotly/Dash.jl/assets/6675409/52d6f817-291a-4993-9556-a56968d0abaf)
