### ISSUE TITLE
Fix Percy CI tests

### ISSUE THREAD

**Issue by etpinard** [plotly/Dash.jl#177]
The [Percy tests](https://github.com/plotly/Dash.jl/blob/f0606e07d2479fd8b5be1da4a6a59656e24acfa3/.circleci/config.yml#L51-L53) are currently failing, for example in https://github.com/plotly/Dash.jl/pull/176:

- https://app.circleci.com/pipelines/github/plotly/Dash.jl/331/workflows/c2e84f85-414a-4a72-9eef-71354bc34ba7/jobs/435
- https://percy.io/plotly/dash.jl/builds/23374298/failed

![image](https://user-images.githubusercontent.com/6675409/204405726-269a3891-80a1-416c-853c-847418a84242.png)

If anyone seeing this has experience with Percy, your help would be much appreciated!

**Comment by etpinard** [comment]
### Update

Now that https://github.com/plotly/Dash.jl/pull/207 is merged, the CircleCI workflow now passes and can successfully upload percy snapshots to percy.io:

- https://app.circleci.com/pipelines/github/plotly/Dash.jl/386/workflows/8bbbdba0-347e-4ec1-88b7-94ef79a3df02/jobs/459
- https://percy.io/plotly/dash.jl/builds/28145762/changed/1564719617?browser=firefox&browser_ids=38%2C39&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=1280

But on the percy.io build page, looks like I can't approve the snapshots and we cannot [reuse the "old" snapshots](https://github.com/plotly/Dash.jl/pull/205#issuecomment-1587999357) either.

So, looks like we'll need help from someone at Plotly in order to resolve this issue.

----

In the meantime, manually asserting that the screenshots look like:

![image](https://github.com/plotly/Dash.jl/assets/6675409/f454a40b-1b78-4fa9-8f22-6dca7bcfc30f)

![image](https://github.com/plotly/Dash.jl/assets/6675409/c5a08e0c-afe4-4f7c-806e-71f86bd1460e)

![image](https://github.com/plotly/Dash.jl/assets/6675409/8f29cac7-8928-4197-b955-2711948c1844)

is better than nothing :smile:

**Comment by alexcjohnson** [comment]
@etpinard I sent you an invite to percy, LMK if that unblocks you!

**Comment by etpinard** [comment]
Thanks @alexcjohnson !! 

I can now approve the baselines and I think I got the [baseline settings](https://percy.io/plotly/dash.jl/settings#advanced) to work correctly with

![image](https://github.com/plotly/Dash.jl/assets/6675409/4b140922-9391-4299-b902-31c4032f133c)

I got a clean pass in https://percy.io/plotly/dash.jl/builds/28183626/unchanged/1566645204?browser=chrome&viewLayout=side-by-side&viewMode=new&width=1280

and I got percy to generate a diff with this patch

```diff
--- a/test/integration/base/jl_render/jltr001r_undo_redo.jl
+++ b/test/integration/base/jl_render/jltr001r_undo_redo.jl
@@ -4,7 +4,8 @@ app = dash(show_undo_redo=true)

 app.layout = html_div() do
  dcc_input(id="a"),
- html_div(id="b")
+ html_div(id="b"),
+ html_h1("SHOULD NOT WORK")
 end
```

https://percy.io/plotly/dash.jl/builds/28184515/changed/1566701020?browser=firefox&browser_ids=38%2C39&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=1280

![image](https://github.com/plotly/Dash.jl/assets/6675409/a5d7b9c6-514f-4489-98d9-4b4d727f80b3)

----

Closing :tada: :tada: :tada:
