### ISSUE TITLE
markdown with latex support

### ISSUE THREAD

**Issue by baxmittens** [plotly/Dash.jl#202]
Is it possible to use markdown with latex support? in the javascript version, there is a flag for that. but it seems not to be implemented in the julia version.

Many thanks.
Greetz max

**Comment by etpinard** [comment]
This will be supported in the upcoming Dash.jl `v1.3.0` release.

Example:

```jl
using Dash

app = dash()

app.layout = html_div() do
    dcc_markdown("\$E=mc^2\$"; mathjax=true),
    dcc_markdown("# An h1 tag with MathJax: \$x=\\int_0^a a^2+1\$", mathjax=true),
    dcc_graph(mathjax=true,
              figure=(data=[(y=[1, 4, 9, 16],)],
                      layout=(xaxis=(title=r"$\sqrt{(n^2(t|T_))}$",),)))
end

run_server(app)
```

gives

![image](https://github.com/plotly/Dash.jl/assets/6675409/1053248b-ffc6-49e6-8819-83d27378be9b)


Updating the resources in https://github.com/plotly/Dash.jl/pull/212 essentially resolved this issue. Closing
