### ISSUE TITLE
Support for subplots produced by PlotlyJS.jl

### ISSUE THREAD

**Issue by rpkyle** [plotly/Dash.jl#23]
As mentioned in https://github.com/plotly/Dash.jl/pull/18#discussion_r423822868, we should eventually consider supporting subplots in Plotly figures, if this is not already possible.

**Comment by sglyon** [comment]
Hey @rpkyle this is a timely issue to open.


We've recently expanded the support for subplots in PlotlyBase.jl and PlotlyJS.jl (check out the new `Subplots` type and the `make_subplots` function!) These are currently best documented here: https://github.com/plotly/plotlyjs.jl-docs/blob/master/julia/subplots.md, but will soon be published to https://plotly.com/julia/subplots

Furthermore, any plot created with PlotlyJS.jl or PlotlyBase.jl can be directly passed as the `figure` argument to `dcc_graph` :tada:!
