### ISSUE TITLE
Why has the DashCoreResources repo been archived?

### ISSUE THREAD

**Issue by etpinard** [plotly/Dash.jl#237]
https://github.com/plotly/DashCoreResources has been archived on June 3, 2024, but Dash.jl depends on it through its artifacts:

https://github.com/plotly/Dash.jl/blob/4d93ee8654a965eb188a7e90fad2f5f4c261c751/Artifacts.toml#L6

Can someone at Plotly un-archived it? 

(I'll cc https://github.com/gvwilson who has recently pushed a commit to Dash.jl)

Thank you!

**Comment by etpinard** [comment]
Ping @gvwilson

**Comment by gvwilson** [comment]
thanks @etpinard - wasn't aware of the build dependency. I'll try to get it unarchived today.

**Comment by etpinard** [comment]
thank you!

**Comment by gvwilson** [comment]
https://github.com/plotly/DashCoreResources has been restored - please let me know if you need anything more.

**Comment by etpinard** [comment]
I get

![image](https://github.com/user-attachments/assets/a6ba3eb4-4f01-4879-95a8-23da36dd83a5)

perhaps the repo is private?

**Comment by gvwilson** [comment]
...right. Should be fixed now - sorry about that.

**Comment by etpinard** [comment]
Great. Thank you!

Could you also grant me push rights to the https://github.com/plotly/DashCoreResources repo?

This is [_Step 0_](https://github.com/plotly/Dash.jl/tree/dev/gen_resources#step-0-get-push-rights-to-dashcoreresources) in the generate-artifacts checklist :smile: . Thank you very much.

**Comment by gvwilson** [comment]
done - please let me know if that does what you need

**Comment by etpinard** [comment]
thanks !!!
