### ISSUE TITLE
UndefVarError: html_div not defined

### ISSUE THREAD

**Issue by birodaniel8** [plotly/Dash.jl#36]
Hi all,

I have added the Dash package to Julia and I am just trying to run the "Basic application" you shared in the readme.md but it fails with "UndefVarError: html_div not defined". I have tried the stable version as well. What am I possibly missing here?

Thanks,
Daniel

**Comment by waralex** [comment]
Hi, @birodaniel8 !
It's my fault - an example from the readme does not fully comply with the current dev. In order for everything to work, add
```
using DashHtmlComponents
using DashCoreComponents
```

I will try to correct the documentation as soon as possible

**Comment by birodaniel8** [comment]
That is working, thank you!
