### ISSUE TITLE
Contour plot has no selection tools

### ISSUE THREAD

**Issue by sharmalay** [plotly/Dash.jl#71]
Hello,

I adapted the example from #60 using the JSON workaround to render a contour plot. As can be seen in the photo there are no rectangle or lasso select tools. Is there an option to enable selection tools somehow?

    using Dash
    using DashCoreComponents
    using DashHtmlComponents
    app = dash(external_stylesheets = ["https://codepen.io/chriddyp/pen/bWLwgP.css"])
    app.layout = html_div() do
        html_h1("Hello Dash"),
        html_div("Dash.jl: Julia interface for Dash"),
        dcc_graph(
            id = "example-graph",
            figure = (
                data = [
                    (x = [1, 2, 3], y = [1, 2, 3], z = [rand(3) for _ in 1:3], type = "contour", name = "SF"),
                ],
                layout = (title = "Dash Data Visualization",),
            ),
        )
    end

    run_server(app, "127.0.0.1", 8050, debug = true)

![contour](https://user-images.githubusercontent.com/1643539/95991548-e59a1e80-0dfa-11eb-8f61-a314e8714351.png)

**Comment by alexcjohnson** [comment]
This would need to be added in plotly.js. This would come along essentially for free with heatmap selection - a longstanding open item that just hasn't bubbled to the top of our list (or been tackled by a community member) yet https://github.com/plotly/plotly.js/issues/170
